on: push
jobs:
    build-node:
        runs-on: ubuntu-latest
        container: php
        steps:
            - run : echo "TESTING"
            - run : php --version
            - uses: actions/checkout@v3
            - run: php app.php